CREATE TABLE `DE_TB_EMP` (
  `EMP_NO` varchar(8) NOT NULL COMMENT '사번',
  `EMP_PASSWD` varchar(20) NOT NULL COMMENT '비밀번호',
  `EMP_NM` varchar(100) NOT NULL COMMENT '성명',
  `EMP_POSTION_CD` varchar(5) NOT NULL COMMENT '직급코드',
  `EMP_OFFICIAL_CD` varchar(5) NOT NULL COMMENT '직책코드',
  `EMP_DEPARTMENT` varchar(50) NOT NULL COMMENT '부서명',
  `EMP_GROUP_CD` varchar(10) NOT NULL COMMENT '그룹코드',
  `MCC_DVS_CD` varchar(20) NOT NULL COMMENT '이동통신사구분코드 010',
  `EMP_CELL_TX_NO` varchar(4) NOT NULL COMMENT '휴대폰국번호',
  `EMP_CELL_SPRTLY_NO` varchar(4) NOT NULL COMMENT '휴대폰개별번호',
  `EMP_TELLNO` varchar(4) DEFAULT NULL COMMENT '내선번호',
  `EMP_EMAIL_ADDR` varchar(50) NOT NULL COMMENT '이메일주소',
  `WORK_GBN_CD` varchar(5) NOT NULL COMMENT '출퇴근구분 5~9pm',
  `GENDER_CD` varchar(5) NOT NULL COMMENT '성별구분',
  `DE_C_DTTI` DATETIME NOT NULL COMMENT '등록일시',
  `DE_C_EMPNO` varchar(8) NOT NULL COMMENT '등록자사번',
  `DE_U_DTTI` DATETIME NOT NULL COMMENT '성명',
  `DE_U_EMPNO` varchar(8) NOT NULL COMMENT '수정자사번',
  PRIMARY KEY (`EMP_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사원테이블';


CREATE TABLE `DE_TB_LOGIN` (
  `EMP_NO` varchar(8) NOT NULL COMMENT '사번',
  `EMP_NM` varchar(100) NOT NULL COMMENT '성명',
  `EMP_LOGIN_DTT` DATETIME NOT NULL COMMENT '마지막 로그인일시',
  `EMP_LOGIN_IP` varchar(20) NOT NULL COMMENT '마지막 로그인IP',
  `DE_C_DTTI` DATETIME NOT NULL COMMENT '등록일시',
  `DE_C_EMPNO` varchar(8) NOT NULL COMMENT '등록자사번',
  `DE_U_DTTI` DATETIME NOT NULL COMMENT '성명',
  `DE_U_EMPNO` varchar(8) NOT NULL COMMENT '수정자사번',
  PRIMARY KEY (`EMP_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='로그인테이블';

CREATE TABLE `DE_TB_TRANS_FEE` (
  `EMP_NO` VARCHAR(8) NOT NULL COMMENT '사번',
  `EMP_NM` VARCHAR(100) NOT NULL COMMENT '성명',
  `TRANS_DTTM` VARCHAR(8) NOT NULL COMMENT '일자 (YYYYMMDD)',
  `TRANS_SEQ` NUMERIC NOT NULL DEFAULT 0 COMMENT '순차',  
  `TRANS_REASON` VARCHAR(200) NOT NULL COMMENT '이용사유',
  `TRANS_START_POINT` VARCHAR(100) NOT NULL COMMENT '출발지',  
  `TRANS_END_POINT` VARCHAR(100) NOT NULL COMMENT '도착지',  
  `TRANS_START_TIME` DATETIME NOT NULL COMMENT '출발시간',  
  `TRANS_END_TIME` DATETIME NOT NULL COMMENT '도착시간',  
  `TRANS_AMT` NUMERIC NOT NULL COMMENT '금액',  
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '비고',    
  `DE_C_DTTI` DATETIME NOT NULL COMMENT '등록일시',
  `DE_C_EMPNO` VARCHAR(8) NOT NULL COMMENT '등록자사번',
  `DE_U_DTTI` DATETIME NOT NULL COMMENT '성명',
  `DE_U_EMPNO` VARCHAR(8) NOT NULL COMMENT '수정자사번',
  PRIMARY KEY (`EMP_NO`, `TRANS_DTTM`, `TRANS_SEQ`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='교통비 관리 테이블';


CREATE TABLE `DE_TB_WORK_OFFICER` (
  `EMP_NO` VARCHAR(8) NOT NULL COMMENT '사번',
  `EMP_NM` VARCHAR(100) NOT NULL COMMENT '성명',
  `WORK_DTTM` VARCHAR(8) NOT NULL COMMENT '작성일자 (YYYYMMDD)',
  `WORK_SEQ` NUMERIC NOT NULL DEFAULT 1 COMMENT '순차',  
  `WORK_CONTENT` VARCHAR(500) NOT NULL COMMENT '내용',
  `WORK_GBN` VARCHAR(5) NOT NULL COMMENT '업무구분',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '비고',  
  `DE_C_DTTI` DATETIME NOT NULL COMMENT '등록일시',
  `DE_C_EMPNO` VARCHAR(8) NOT NULL COMMENT '등록자사번',
  `DE_U_DTTI` DATETIME NOT NULL COMMENT '성명',
  `DE_U_EMPNO` VARCHAR(8) NOT NULL COMMENT '수정자사번',
  PRIMARY KEY (`EMP_NO`, `WORK_DTTM`, `WORK_SEQ`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='업무 관리 테이블';


CREATE TABLE `DE_TB_CODE` (
  `MST_CODE` VARCHAR(5) NOT NULL COMMENT '마스터 코드',
  `MST_CODE_NM` VARCHAR(50) NOT NULL COMMENT '마스터 코드명',
  `SUB_CODE` VARCHAR(5) NOT NULL COMMENT '서브 코드',
  `SUB_CODE_NM` VARCHAR(50) NOT NULL COMMENT '서브 코드명',
  `BUFFER_VAL1` VARCHAR(20) DEFAULT NULL COMMENT '기타1',
  `BUFFER_VAL2` VARCHAR(20) DEFAULT NULL COMMENT '기타2',
  `BUFFER_VAL3` VARCHAR(20) DEFAULT NULL COMMENT '기타3',
  `DE_C_DTTI` DATETIME NOT NULL COMMENT '등록일시',
  `DE_C_EMPNO` VARCHAR(8) NOT NULL COMMENT '등록자사번',
  `DE_U_DTTI` DATETIME NOT NULL COMMENT '성명',
  `DE_U_EMPNO` VARCHAR(8) NOT NULL COMMENT '수정자사번',
  PRIMARY KEY (`MST_CODE`, `SUB_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='공통 코드 테이블';



INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0100', '직급', 'S0010', '사원', '', '', '', NOW(), '88888888', NOW(), '88888888');
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0100', '직급', 'S0020', '대리', '', '', '', NOW(), '88888888', NOW(), '88888888');
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0100', '직급', 'S0030', '책임', '', '', '', NOW(), '88888888', NOW(), '88888888');		
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0100', '직급', 'S0040', '수석', '', '', '', NOW(), '88888888', NOW(), '88888888');	
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0100', '직급', 'S0050', '이사', '', '', '', NOW(), '88888888', NOW(), '88888888');			
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0100', '직급', 'S0060', '상무', '', '', '', NOW(), '88888888', NOW(), '88888888');				
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0100', '직급', 'S0070', '전무', '', '', '', NOW(), '88888888', NOW(), '88888888');					
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0200', '직책', 'S0010', '팀원', '', '', '', NOW(), '88888888', NOW(), '88888888');
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0200', '직책', 'S0020', '팀장', '', '', '', NOW(), '88888888', NOW(), '88888888');	
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0200', '직책', 'S0030', '담당', '', '', '', NOW(), '88888888', NOW(), '88888888');		
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0200', '직책', 'S0040', '본부장', '', '', '', NOW(), '88888888', NOW(), '88888888');
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0200', '직책', 'S0050', '부문장', '', '', '', NOW(), '88888888', NOW(), '88888888');				
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0200', '직책', 'S0060', '대표', '', '', '', NOW(), '88888888', NOW(), '88888888');
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0300', '그룹', 'S0010', '1그룹', '', '', '', NOW(), '88888888', NOW(), '88888888');			
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0300', '그룹', 'S0020', '2그룹', '', '', '', NOW(), '88888888', NOW(), '88888888');				
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0400', '출퇴근구분', 'S0010', '8~17', '', '', '', NOW(), '88888888', NOW(), '88888888');
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0400', '출퇴근구분', 'S0020', '9~18', '', '', '', NOW(), '88888888', NOW(), '88888888');				
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0400', '출퇴근구분', 'S0030', '10~19', '', '', '', NOW(), '88888888', NOW(), '88888888');					
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0500', '성별구분', 'S0010', '남성', '', '', '', NOW(), '88888888', NOW(), '88888888');	
INSERT INTO `de_tb_code` 
	(`MST_CODE`, `MST_CODE_NM`, `SUB_CODE`, `SUB_CODE_NM`, `BUFFER_VAL1`, `BUFFER_VAL2`, `BUFFER_VAL3`, `DE_C_DTTI`, `DE_C_EMPNO`, `DE_U_DTTI`, `DE_U_EMPNO`)
VALUES
	('M0500', '성별구분', 'S0020', '여성', '', '', '', NOW(), '88888888', NOW(), '88888888');		